# Generated by Django 4.2.8 on 2023-12-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível')], default='D', max_length=12),
        ),
    ]
